# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'export_abc_options.ui'
#
# Created: Thu Jul 18 20:39:28 2019
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog_exportalembicoptions(object):
    def setupUi(self, Dialog_exportalembicoptions):
        Dialog_exportalembicoptions.setObjectName("Dialog_exportalembicoptions")
        Dialog_exportalembicoptions.resize(382, 431)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/settings-work-tool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog_exportalembicoptions.setWindowIcon(icon)
        Dialog_exportalembicoptions.setStyleSheet("background-color:rgb(50, 50, 50)")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog_exportalembicoptions)
        self.verticalLayout_3.setContentsMargins(7, 7, 7, 7)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_top = QtWidgets.QFrame(Dialog_exportalembicoptions)
        self.frame_top.setStyleSheet("background-color:rgb(70, 70, 70);\n"
"border-radius:5px;")
        self.frame_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_top)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget = QtWidgets.QWidget(self.frame_top)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(350, 20))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget.setBaseSize(QtCore.QSize(0, 0))
        self.widget.setObjectName("widget")
        self.gridLayout_2.addWidget(self.widget, 1, 0, 1, 4)
        self.groupBox_advancedoptions = QtWidgets.QGroupBox(self.frame_top)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(70, 70, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(70, 70, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(70, 70, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(70, 70, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(70, 70, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(70, 70, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(70, 70, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(70, 70, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(70, 70, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.groupBox_advancedoptions.setPalette(palette)
        self.groupBox_advancedoptions.setStyleSheet("QGroupBox{border:1px solid gray; width:5px;border-radius:5px; padding:8px 16px;}")
        self.groupBox_advancedoptions.setObjectName("groupBox_advancedoptions")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_advancedoptions)
        self.verticalLayout_4.setContentsMargins(7, 7, 7, 7)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_colorSet = QtWidgets.QCheckBox(self.groupBox_advancedoptions)
        self.checkBox_colorSet.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_colorSet.sizePolicy().hasHeightForWidth())
        self.checkBox_colorSet.setSizePolicy(sizePolicy)
        self.checkBox_colorSet.setAcceptDrops(False)
        self.checkBox_colorSet.setAutoFillBackground(False)
        self.checkBox_colorSet.setChecked(True)
        self.checkBox_colorSet.setTristate(False)
        self.checkBox_colorSet.setObjectName("checkBox_colorSet")
        self.verticalLayout.addWidget(self.checkBox_colorSet)
        self.checkBox_worldSpace = QtWidgets.QCheckBox(self.groupBox_advancedoptions)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_worldSpace.sizePolicy().hasHeightForWidth())
        self.checkBox_worldSpace.setSizePolicy(sizePolicy)
        self.checkBox_worldSpace.setChecked(True)
        self.checkBox_worldSpace.setObjectName("checkBox_worldSpace")
        self.verticalLayout.addWidget(self.checkBox_worldSpace)
        self.checkBox_uvSets = QtWidgets.QCheckBox(self.groupBox_advancedoptions)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_uvSets.sizePolicy().hasHeightForWidth())
        self.checkBox_uvSets.setSizePolicy(sizePolicy)
        self.checkBox_uvSets.setChecked(True)
        self.checkBox_uvSets.setObjectName("checkBox_uvSets")
        self.verticalLayout.addWidget(self.checkBox_uvSets)
        self.checkBox_visibility = QtWidgets.QCheckBox(self.groupBox_advancedoptions)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_visibility.sizePolicy().hasHeightForWidth())
        self.checkBox_visibility.setSizePolicy(sizePolicy)
        self.checkBox_visibility.setChecked(False)
        self.checkBox_visibility.setObjectName("checkBox_visibility")
        self.verticalLayout.addWidget(self.checkBox_visibility)
        self.checkBox_creases = QtWidgets.QCheckBox(self.groupBox_advancedoptions)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_creases.sizePolicy().hasHeightForWidth())
        self.checkBox_creases.setSizePolicy(sizePolicy)
        self.checkBox_creases.setChecked(True)
        self.checkBox_creases.setObjectName("checkBox_creases")
        self.verticalLayout.addWidget(self.checkBox_creases)
        self.checkBox_faceSets = QtWidgets.QCheckBox(self.groupBox_advancedoptions)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_faceSets.sizePolicy().hasHeightForWidth())
        self.checkBox_faceSets.setSizePolicy(sizePolicy)
        self.checkBox_faceSets.setChecked(True)
        self.checkBox_faceSets.setObjectName("checkBox_faceSets")
        self.verticalLayout.addWidget(self.checkBox_faceSets)
        self.checkBox_uv = QtWidgets.QCheckBox(self.groupBox_advancedoptions)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_uv.sizePolicy().hasHeightForWidth())
        self.checkBox_uv.setSizePolicy(sizePolicy)
        self.checkBox_uv.setChecked(True)
        self.checkBox_uv.setObjectName("checkBox_uv")
        self.verticalLayout.addWidget(self.checkBox_uv)
        self.checkBox_8 = QtWidgets.QCheckBox(self.groupBox_advancedoptions)
        self.checkBox_8.setObjectName("checkBox_8")
        self.verticalLayout.addWidget(self.checkBox_8)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.gridLayout_2.addWidget(self.groupBox_advancedoptions, 2, 0, 2, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_framestart = QtWidgets.QLineEdit(self.frame_top)
        self.lineEdit_framestart.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_framestart.setStyleSheet("QLineEdit{border:1px solid gray; width:5px;border-radius:5px; padding:2px 4px;}")
        self.lineEdit_framestart.setObjectName("lineEdit_framestart")
        self.gridLayout.addWidget(self.lineEdit_framestart, 1, 1, 1, 1)
        self.label_framerange = QtWidgets.QLabel(self.frame_top)
        self.label_framerange.setStyleSheet("")
        self.label_framerange.setObjectName("label_framerange")
        self.gridLayout.addWidget(self.label_framerange, 1, 0, 1, 1)
        self.lineEdit_framestep = QtWidgets.QLineEdit(self.frame_top)
        self.lineEdit_framestep.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_framestep.setStyleSheet("QLineEdit{border:1px solid gray; width:5px;border-radius:5px; padding:2px 4px;}")
        self.lineEdit_framestep.setObjectName("lineEdit_framestep")
        self.gridLayout.addWidget(self.lineEdit_framestep, 1, 3, 1, 1)
        self.lineEdit_frameend = QtWidgets.QLineEdit(self.frame_top)
        self.lineEdit_frameend.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_frameend.setStyleSheet("QLineEdit{border:1px solid gray; width:5px;border-radius:5px; padding:2px 4px;}")
        self.lineEdit_frameend.setObjectName("lineEdit_frameend")
        self.gridLayout.addWidget(self.lineEdit_frameend, 1, 2, 1, 1)
        self.label_start = QtWidgets.QLabel(self.frame_top)
        self.label_start.setObjectName("label_start")
        self.gridLayout.addWidget(self.label_start, 0, 1, 1, 1)
        self.label_end = QtWidgets.QLabel(self.frame_top)
        self.label_end.setObjectName("label_end")
        self.gridLayout.addWidget(self.label_end, 0, 2, 1, 1)
        self.label_step = QtWidgets.QLabel(self.frame_top)
        self.label_step.setObjectName("label_step")
        self.gridLayout.addWidget(self.label_step, 0, 3, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 0, 1, 3)
        self.frame_downmiddle = QtWidgets.QFrame(self.frame_top)
        self.frame_downmiddle.setMinimumSize(QtCore.QSize(50, 50))
        self.frame_downmiddle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_downmiddle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_downmiddle.setObjectName("frame_downmiddle")
        self.gridLayout_2.addWidget(self.frame_downmiddle, 2, 1, 3, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 4, 0, 1, 1)
        self.frame_topleft = QtWidgets.QFrame(self.frame_top)
        self.frame_topleft.setMinimumSize(QtCore.QSize(20, 20))
        self.frame_topleft.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_topleft.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_topleft.setObjectName("frame_topleft")
        self.gridLayout_2.addWidget(self.frame_topleft, 0, 3, 1, 1)
        self.groupBox_format = QtWidgets.QGroupBox(self.frame_top)
        self.groupBox_format.setStyleSheet("QGroupBox{border:1px solid gray; width:5px;border-radius:5px; padding:8px 16px;}")
        self.groupBox_format.setObjectName("groupBox_format")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_format)
        self.verticalLayout_5.setContentsMargins(7, 7, 7, 7)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton_hdf5 = QtWidgets.QRadioButton(self.groupBox_format)
        self.radioButton_hdf5.setObjectName("radioButton_hdf5")
        self.verticalLayout_2.addWidget(self.radioButton_hdf5)
        self.radioButton_Ogawa = QtWidgets.QRadioButton(self.groupBox_format)
        self.radioButton_Ogawa.setObjectName("radioButton_Ogawa")
        self.radioButton_Ogawa.setChecked(True)
        self.verticalLayout_2.addWidget(self.radioButton_Ogawa)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.gridLayout_2.addWidget(self.groupBox_format, 2, 2, 1, 2)
        self.frame_downright = QtWidgets.QFrame(self.frame_top)
        self.frame_downright.setMinimumSize(QtCore.QSize(50, 100))
        self.frame_downright.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_downright.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_downright.setObjectName("frame_downright")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_downright)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_scene = QtWidgets.QLabel(self.frame_downright)
        self.label_scene.setObjectName("label_scene")
        self.gridLayout_3.addWidget(self.label_scene, 0, 0, 1, 1)
        self.lineEdit_scene = QtWidgets.QLineEdit(self.frame_downright)
        font = QtGui.QFont()
        font.setFamily("Alef")
        font.setWeight(75)
        font.setBold(True)
        self.lineEdit_scene.setFont(font)
        self.lineEdit_scene.setStyleSheet("background-color:rgb(165, 165, 165)")
        self.lineEdit_scene.setObjectName("lineEdit_scene")
        self.gridLayout_3.addWidget(self.lineEdit_scene, 0, 1, 1, 1)
        self.label_camera = QtWidgets.QLabel(self.frame_downright)
        self.label_camera.setObjectName("label_camera")
        self.gridLayout_3.addWidget(self.label_camera, 1, 0, 1, 1)
        self.lineEdit_camera = QtWidgets.QLineEdit(self.frame_downright)
        font = QtGui.QFont()
        font.setFamily("Alef")
        font.setWeight(75)
        font.setBold(True)
        self.lineEdit_camera.setFont(font)
        self.lineEdit_camera.setStyleSheet("background-color:rgb(165, 165, 165)")
        self.lineEdit_camera.setObjectName("lineEdit_camera")
        self.gridLayout_3.addWidget(self.lineEdit_camera, 1, 1, 1, 1)
        self.label_prop = QtWidgets.QLabel(self.frame_downright)
        self.label_prop.setObjectName("label_prop")
        self.gridLayout_3.addWidget(self.label_prop, 2, 0, 1, 1)
        self.lineEdit_prop = QtWidgets.QLineEdit(self.frame_downright)
        font = QtGui.QFont()
        font.setFamily("Alef")
        font.setWeight(75)
        font.setBold(True)
        self.lineEdit_prop.setFont(font)
        self.lineEdit_prop.setStyleSheet("background-color:rgb(165, 165, 165)")
        self.lineEdit_prop.setObjectName("lineEdit_prop")
        self.gridLayout_3.addWidget(self.lineEdit_prop, 2, 1, 1, 1)
        self.lineEdit_character = QtWidgets.QLineEdit(self.frame_downright)
        font = QtGui.QFont()
        font.setFamily("Alef")
        font.setWeight(75)
        font.setBold(True)
        self.lineEdit_character.setFont(font)
        self.lineEdit_character.setStyleSheet("background-color:rgb(165, 165, 165)")
        self.lineEdit_character.setObjectName("lineEdit_character")
        self.gridLayout_3.addWidget(self.lineEdit_character, 3, 1, 1, 1)
        self.label_character = QtWidgets.QLabel(self.frame_downright)
        self.label_character.setObjectName("label_character")
        self.gridLayout_3.addWidget(self.label_character, 3, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_downright, 3, 2, 2, 2)
        self.verticalLayout_3.addWidget(self.frame_top)
        self.frame_down = QtWidgets.QFrame(Dialog_exportalembicoptions)
        self.frame_down.setMaximumSize(QtCore.QSize(16777215, 72))
        self.frame_down.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_down.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_down.setObjectName("frame_down")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_down)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.pushButton_save = QtWidgets.QPushButton(self.frame_down)
        self.pushButton_save.setMinimumSize(QtCore.QSize(70, 20))
        self.pushButton_save.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton_save.setBaseSize(QtCore.QSize(0, 0))
        self.pushButton_save.setStyleSheet("QPushButton{background:rgb(94, 94, 94);border-radius:5px;}QPushButton:hover{background:rgb(15, 185, 15);}\n"
"")
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout.addWidget(self.pushButton_save)
        self.pushButton_cancle = QtWidgets.QPushButton(self.frame_down)
        self.pushButton_cancle.setMinimumSize(QtCore.QSize(70, 20))
        self.pushButton_cancle.setStyleSheet("QPushButton{background:rgb(94, 94, 94);border-radius:5px;}QPushButton:hover{background:rgb(185, 15, 15);}\n"
"")
        self.pushButton_cancle.setObjectName("pushButton_cancle")
        self.horizontalLayout.addWidget(self.pushButton_cancle)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addWidget(self.frame_down)

        self.retranslateUi(Dialog_exportalembicoptions)
        QtCore.QMetaObject.connectSlotsByName(Dialog_exportalembicoptions)

    def retranslateUi(self, Dialog_exportalembicoptions):
        Dialog_exportalembicoptions.setWindowTitle(QtWidgets.QApplication.translate("Dialog_exportalembicoptions", "Export Alembic Options (No best, only better)", None, -1))
        self.groupBox_advancedoptions.setTitle(QtWidgets.QApplication.translate("Dialog_exportalembicoptions", "Advanced Options", None, -1))
        self.checkBox_colorSet.setText(QtWidgets.QApplication.translate("Dialog_exportalembicoptions", "colorSet", None, -1))
        self.checkBox_worldSpace.setText(QtWidgets.QApplication.translate("Dialog_exportalembicoptions", "worldSpace", None, -1))
        self.checkBox_uvSets.setText(QtWidgets.QApplication.translate("Dialog_exportalembicoptions", "uvSets", None, -1))
        self.checkBox_visibility.setText(QtWidgets.QApplication.translate("Dialog_exportalembicoptions", "visibility", None, -1))
        self.checkBox_creases.setText(QtWidgets.QApplication.translate("Dialog_exportalembicoptions", "creases", None, -1))
        self.checkBox_faceSets.setText(QtWidgets.QApplication.translate("Dialog_exportalembicoptions", "faceSets", None, -1))
        self.checkBox_uv.setText(QtWidgets.QApplication.translate("Dialog_exportalembicoptions", "UV", None, -1))
        self.checkBox_8.setText(QtWidgets.QApplication.translate("Dialog_exportalembicoptions", ".", None, -1))
        self.label_framerange.setToolTip(QtWidgets.QApplication.translate("Dialog_exportalembicoptions", "The default setting is based on Maya\'s project. If it is not required, it does not need to be set", None, -1))
        self.label_framerange.setStatusTip(QtWidgets.QApplication.translate("Dialog_exportalembicoptions", "The default setting is based on Maya\'s project. If it is not required, it does not need to be set", None, -1))
        self.label_framerange.setWhatsThis(QtWidgets.QApplication.translate("Dialog_exportalembicoptions", "The default setting is based on Maya\'s project. If it is not required, it does not need to be set", None, -1))
        self.label_framerange.setText(QtWidgets.QApplication.translate("Dialog_exportalembicoptions", "Frame Range", None, -1))
        self.label_start.setText(QtWidgets.QApplication.translate("Dialog_exportalembicoptions", "Start", None, -1))
        self.label_end.setText(QtWidgets.QApplication.translate("Dialog_exportalembicoptions", "End", None, -1))
        self.label_step.setText(QtWidgets.QApplication.translate("Dialog_exportalembicoptions", "Step", None, -1))
        self.groupBox_format.setTitle(QtWidgets.QApplication.translate("Dialog_exportalembicoptions", "Format", None, -1))
        self.radioButton_hdf5.setText(QtWidgets.QApplication.translate("Dialog_exportalembicoptions", "HDF5", None, -1))
        self.radioButton_Ogawa.setText(QtWidgets.QApplication.translate("Dialog_exportalembicoptions", "Ogawa", None, -1))
        self.label_scene.setText(QtWidgets.QApplication.translate("Dialog_exportalembicoptions", "Scene", None, -1))
        self.lineEdit_scene.setText(QtWidgets.QApplication.translate("Dialog_exportalembicoptions", "Scene", None, -1))
        self.label_camera.setText(QtWidgets.QApplication.translate("Dialog_exportalembicoptions", "Camera", None, -1))
        self.lineEdit_camera.setText(QtWidgets.QApplication.translate("Dialog_exportalembicoptions", "Camera", None, -1))
        self.label_prop.setText(QtWidgets.QApplication.translate("Dialog_exportalembicoptions", "Prop", None, -1))
        self.lineEdit_prop.setText(QtWidgets.QApplication.translate("Dialog_exportalembicoptions", "Prop", None, -1))
        self.lineEdit_character.setText(QtWidgets.QApplication.translate("Dialog_exportalembicoptions", "Character", None, -1))
        self.label_character.setText(QtWidgets.QApplication.translate("Dialog_exportalembicoptions", "Character", None, -1))
        self.pushButton_save.setText(QtWidgets.QApplication.translate("Dialog_exportalembicoptions", "Save", None, -1))
        self.pushButton_cancle.setText(QtWidgets.QApplication.translate("Dialog_exportalembicoptions", "Cancle", None, -1))

