# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow_v02.ui',
# licensing of 'mainwindow_v02.ui' applies.
#
# Created: Sat Jul 13 22:41:38 2019
#      by: pyside2-uic  running on PySide2 5.12.3
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(780, 824)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/cat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color:rgb(70, 70, 70)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(5, 1, 7, 7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget_main = QtWidgets.QTabWidget(self.widget)
        self.tabWidget_main.setStatusTip("")
        self.tabWidget_main.setStyleSheet("background-color:rgb(60, 60, 60)")
        self.tabWidget_main.setObjectName("tabWidget_main")
        self.tab_import = QtWidgets.QWidget()
        self.tab_import.setObjectName("tab_import")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_import)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.tab_import)
        self.widget_2.setStyleSheet("background-color:rgb(65, 65, 65)")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_filepath = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_filepath.setStyleSheet("QLineEdit{border:1px solid gray; width:300px;border-radius:5px; padding:2px 4px;}")
        self.lineEdit_filepath.setObjectName("lineEdit_filepath")
        self.gridLayout.addWidget(self.lineEdit_filepath, 0, 1, 1, 1)
        self.label_file_path = QtWidgets.QLabel(self.widget_2)
        self.label_file_path.setStyleSheet("font: 75 9pt \"Alef\";")
        self.label_file_path.setObjectName("label_file_path")
        self.gridLayout.addWidget(self.label_file_path, 0, 0, 1, 1)
        self.pushButton_search = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_search.setStyleSheet("QPushButton:hover{background:rgb(150, 150, 150);}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/magnifier.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_search.setIcon(icon1)
        self.pushButton_search.setObjectName("pushButton_search")
        self.gridLayout.addWidget(self.pushButton_search, 0, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(7)
        self.horizontalLayout_6.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_left = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_left.sizePolicy().hasHeightForWidth())
        self.pushButton_left.setSizePolicy(sizePolicy)
        self.pushButton_left.setMinimumSize(QtCore.QSize(20, 20))
        self.pushButton_left.setBaseSize(QtCore.QSize(20, 20))
        self.pushButton_left.setStyleSheet("QPushButton{background:rgb(94, 94, 94);border-radius:5px;}QPushButton:hover{background:rgb(15, 185, 15);}\n"
"")
        self.pushButton_left.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/left-arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_left.setIcon(icon2)
        self.pushButton_left.setObjectName("pushButton_left")
        self.horizontalLayout_6.addWidget(self.pushButton_left)
        self.pushButton_right = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_right.sizePolicy().hasHeightForWidth())
        self.pushButton_right.setSizePolicy(sizePolicy)
        self.pushButton_right.setMinimumSize(QtCore.QSize(20, 20))
        self.pushButton_right.setBaseSize(QtCore.QSize(20, 20))
        self.pushButton_right.setStyleSheet("QPushButton{background:rgb(94, 94, 94);border-radius:5px;}QPushButton:hover{background:rgb(15, 185, 15);}\n"
"")
        self.pushButton_right.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/right-arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_right.setIcon(icon3)
        self.pushButton_right.setFlat(False)
        self.pushButton_right.setObjectName("pushButton_right")
        self.horizontalLayout_6.addWidget(self.pushButton_right)
        self.comboBox_filterlist = QtWidgets.QComboBox(self.widget_2)
        self.comboBox_filterlist.setStyleSheet("")
        self.comboBox_filterlist.setObjectName("comboBox_filterlist")
        self.comboBox_filterlist.addItem("")
        self.comboBox_filterlist.addItem("")
        self.comboBox_filterlist.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox_filterlist)
        spacerItem = QtWidgets.QSpacerItem(399, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.listView = QtWidgets.QListView(self.widget_2)
        self.listView.setStyleSheet("QPushButton:hover{background:rgb(15, 185, 15);}")
        self.listView.setObjectName("listView")
        self.verticalLayout_3.addWidget(self.listView)
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setStyleSheet("background-color:rgb(75, 75, 75)")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.comboBox_export_mode = QtWidgets.QComboBox(self.widget_3)
        self.comboBox_export_mode.setObjectName("comboBox_export_mode")
        self.comboBox_export_mode.addItem("")
        self.comboBox_export_mode.addItem("")
        self.comboBox_export_mode.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_export_mode)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_3.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setStyleSheet("background-color:rgb(75, 75, 75)")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_namsepace = QtWidgets.QLabel(self.widget_4)
        self.label_namsepace.setStyleSheet("font: 75 9pt \"Alef\";")
        self.label_namsepace.setObjectName("label_namsepace")
        self.gridLayout_2.addWidget(self.label_namsepace, 0, 2, 1, 1)
        self.lineEdit_namespace = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_namespace.setStyleSheet("QLineEdit{border:1px solid gray; width:50px;border-radius:5px; padding:2px 4px;}")
        self.lineEdit_namespace.setObjectName("lineEdit_namespace")
        self.gridLayout_2.addWidget(self.lineEdit_namespace, 0, 3, 1, 1)
        self.lineEdit_exportname = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_exportname.setStyleSheet("QLineEdit{border:1px solid gray; width:200px;border-radius:5px; padding:2px 4px;}")
        self.lineEdit_exportname.setObjectName("lineEdit_exportname")
        self.gridLayout_2.addWidget(self.lineEdit_exportname, 0, 1, 1, 1)
        self.label_export_name = QtWidgets.QLabel(self.widget_4)
        self.label_export_name.setStyleSheet("font: 75 9pt \"Alef\";")
        self.label_export_name.setObjectName("label_export_name")
        self.gridLayout_2.addWidget(self.label_export_name, 0, 0, 1, 1)
        self.lineEdit_exportpath = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_exportpath.setStyleSheet("QLineEdit{border:1px solid gray; width:200px;border-radius:5px; padding:2px 4px;}")
        self.lineEdit_exportpath.setText("")
        self.lineEdit_exportpath.setObjectName("lineEdit_exportpath")
        self.gridLayout_2.addWidget(self.lineEdit_exportpath, 1, 1, 1, 3)
        self.label_exportpath = QtWidgets.QLabel(self.widget_4)
        self.label_exportpath.setWhatsThis("")
        self.label_exportpath.setStyleSheet("font: 75 9pt \"Alef\";")
        self.label_exportpath.setObjectName("label_exportpath")
        self.gridLayout_2.addWidget(self.label_exportpath, 1, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget_4)
        self.label.setStyleSheet("font: 75 9pt \"Alef\";")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.checkBox_scene = QtWidgets.QCheckBox(self.widget_4)
        self.checkBox_scene.setObjectName("checkBox_scene")
        self.horizontalLayout.addWidget(self.checkBox_scene)
        self.checkBox_camera = QtWidgets.QCheckBox(self.widget_4)
        self.checkBox_camera.setObjectName("checkBox_camera")
        self.horizontalLayout.addWidget(self.checkBox_camera)
        self.checkBox_prop = QtWidgets.QCheckBox(self.widget_4)
        self.checkBox_prop.setObjectName("checkBox_prop")
        self.horizontalLayout.addWidget(self.checkBox_prop)
        self.checkBox_chracter = QtWidgets.QCheckBox(self.widget_4)
        self.checkBox_chracter.setObjectName("checkBox_chracter")
        self.horizontalLayout.addWidget(self.checkBox_chracter)
        spacerItem3 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.progressBar = QtWidgets.QProgressBar(self.widget_4)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_4.addWidget(self.progressBar)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.verticalLayout_3.addWidget(self.widget_4)
        self.verticalLayout_2.addWidget(self.widget_2)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/import.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_main.addTab(self.tab_import, icon4, "")
        self.tab_undefined01 = QtWidgets.QWidget()
        self.tab_undefined01.setObjectName("tab_undefined01")
        self.tabWidget_main.addTab(self.tab_undefined01, "")
        self.tab_undefined02 = QtWidgets.QWidget()
        self.tab_undefined02.setObjectName("tab_undefined02")
        self.tabWidget_main.addTab(self.tab_undefined02, "")
        self.horizontalLayout_2.addWidget(self.tabWidget_main)
        self.horizontalLayout_4.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 780, 26))
        self.menubar.setStyleSheet("background-color:rgb(60, 60, 60)")
        self.menubar.setObjectName("menubar")
        self.menu_Setting = QtWidgets.QMenu(self.menubar)
        self.menu_Setting.setObjectName("menu_Setting")
        self.menu_About = QtWidgets.QMenu(self.menubar)
        self.menu_About.setObjectName("menu_About")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dockWidget_om = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget_om.sizePolicy().hasHeightForWidth())
        self.dockWidget_om.setSizePolicy(sizePolicy)
        self.dockWidget_om.setMinimumSize(QtCore.QSize(142, 164))
        self.dockWidget_om.setFloating(False)
        self.dockWidget_om.setObjectName("dockWidget_om")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_leftside = QtWidgets.QWidget(self.dockWidgetContents_2)
        self.widget_leftside.setObjectName("widget_leftside")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_leftside)
        self.verticalLayout_5.setContentsMargins(7, 7, 7, 7)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_action = QtWidgets.QPushButton(self.widget_leftside)
        self.pushButton_action.setMinimumSize(QtCore.QSize(50, 0))
        self.pushButton_action.setStyleSheet("QPushButton{background:rgb(94, 94, 94);border-radius:5px;}QPushButton:hover{background:rgb(185, 15, 15);}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/hammer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_action.setIcon(icon5)
        self.pushButton_action.setObjectName("pushButton_action")
        self.verticalLayout_5.addWidget(self.pushButton_action)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem6)
        self.pushButton_refresh = QtWidgets.QPushButton(self.widget_leftside)
        self.pushButton_refresh.setMinimumSize(QtCore.QSize(50, 0))
        self.pushButton_refresh.setStyleSheet("QPushButton{background:rgb(94, 94, 94);border-radius:5px;}QPushButton:hover{background:green;}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_refresh.setIcon(icon6)
        self.pushButton_refresh.setObjectName("pushButton_refresh")
        self.verticalLayout_5.addWidget(self.pushButton_refresh)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem7)
        self.verticalLayout.addWidget(self.widget_leftside)
        self.dockWidget_om.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_om)
        self.actionSetting = QtWidgets.QAction(MainWindow)
        self.actionSetting.setCheckable(False)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/settings-work-tool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSetting.setIcon(icon7)
        self.actionSetting.setStatusTip("")
        self.actionSetting.setVisible(True)
        self.actionSetting.setObjectName("actionSetting")
        self.actionAboutThis = QtWidgets.QAction(MainWindow)
        self.actionAboutThis.setObjectName("actionAboutThis")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionDefault = QtWidgets.QAction(MainWindow)
        self.actionDefault.setObjectName("actionDefault")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.menu_Setting.addAction(self.actionDefault)
        self.menu_About.addAction(self.actionAboutThis)
        self.menu_File.addAction(self.actionSave)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Setting.menuAction())
        self.menubar.addAction(self.menu_About.menuAction())
        self.toolBar.addAction(self.actionSetting)

        self.retranslateUi(MainWindow)
        self.tabWidget_main.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Automation (Do your better)", None, -1))
        self.label_file_path.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "The folder to search", None, -1))
        self.label_file_path.setText(QtWidgets.QApplication.translate("MainWindow", "File Path", None, -1))
        self.pushButton_search.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Tips: Start Search", None, -1))
        self.pushButton_search.setText(QtWidgets.QApplication.translate("MainWindow", "Search", None, -1))
        self.pushButton_left.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Tips: Switch to Top Level", None, -1))
        self.pushButton_right.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Tips: The next level", None, -1))
        self.comboBox_filterlist.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Tips: Filltration", None, -1))
        self.comboBox_filterlist.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "*", None, -1))
        self.comboBox_filterlist.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "*.mb;*.ma", None, -1))
        self.comboBox_filterlist.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "*.hip", None, -1))
        self.listView.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Tips:Select the file you will export", None, -1))
        self.comboBox_export_mode.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Tips: Export mode", None, -1))
        self.comboBox_export_mode.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "SelectCheck", None, -1))
        self.comboBox_export_mode.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "ByName", None, -1))
        self.comboBox_export_mode.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "All", None, -1))
        self.label_namsepace.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Tips: namespace in maya", None, -1))
        self.label_namsepace.setText(QtWidgets.QApplication.translate("MainWindow", "namesapce", None, -1))
        self.label_export_name.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Tips: The name to look for is in Maya", None, -1))
        self.label_export_name.setText(QtWidgets.QApplication.translate("MainWindow", "Export Name", None, -1))
        self.label_exportpath.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Tips: default is current houdini project", None, -1))
        self.label_exportpath.setText(QtWidgets.QApplication.translate("MainWindow", "Export Path", None, -1))
        self.label.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Tips: Export Options", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Option", None, -1))
        self.checkBox_scene.setText(QtWidgets.QApplication.translate("MainWindow", "Scene", None, -1))
        self.checkBox_camera.setText(QtWidgets.QApplication.translate("MainWindow", "Camera", None, -1))
        self.checkBox_prop.setText(QtWidgets.QApplication.translate("MainWindow", "Prop", None, -1))
        self.checkBox_chracter.setText(QtWidgets.QApplication.translate("MainWindow", "Chracter", None, -1))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab_import), QtWidgets.QApplication.translate("MainWindow", "Import", None, -1))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab_undefined01), QtWidgets.QApplication.translate("MainWindow", "Undefined_1", None, -1))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab_undefined02), QtWidgets.QApplication.translate("MainWindow", "Undefined_2", None, -1))
        self.menu_Setting.setTitle(QtWidgets.QApplication.translate("MainWindow", "&Setting", None, -1))
        self.menu_About.setTitle(QtWidgets.QApplication.translate("MainWindow", "&About", None, -1))
        self.menu_File.setTitle(QtWidgets.QApplication.translate("MainWindow", "&File", None, -1))
        self.toolBar.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "toolBar", None, -1))
        self.dockWidget_om.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Instant Fall", None, -1))
        self.pushButton_action.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Tips: Export operation", None, -1))
        self.pushButton_action.setText(QtWidgets.QApplication.translate("MainWindow", "Action", None, -1))
        self.pushButton_refresh.setText(QtWidgets.QApplication.translate("MainWindow", "Refresh", None, -1))
        self.actionSetting.setText(QtWidgets.QApplication.translate("MainWindow", "Setting", None, -1))
        self.actionAboutThis.setText(QtWidgets.QApplication.translate("MainWindow", "About Automation", None, -1))
        self.actionAbout.setText(QtWidgets.QApplication.translate("MainWindow", "About", None, -1))
        self.actionDefault.setText(QtWidgets.QApplication.translate("MainWindow", "Default", None, -1))
        self.actionSave.setText(QtWidgets.QApplication.translate("MainWindow", "Save", None, -1))

import resource_rc